language: java
jdk:
- openjdk11
dist: trusty
services:
- mysql
before_install:
- chmod +x mvnw
- sudo mysql -e 'CREATE DATABASE b2w;'

after_success:
- sudo mysql -uroot --password='' b2w < bkp.sql
- bash <(curl -s https://codecov.io/bash)
